name: flutter_authentication_screens_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.2+6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Web service handler
  dio: ^5.7.0

  # State management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  # Dependency injection
  get_it: ^8.0.3

  # Routing
  go_router: ^14.8.1

  # Local storage
  shared_preferences: ^2.5.3

  # Localization
  slang: &slang_version 4.6.0
  slang_flutter: *slang_version

  # Provides internationalization and localization facilities
  intl: ^0.19.0

  # SVG file viewer
  flutter_svg: ^2.0.7

  # Show images from the internet and keep them in the cache directory
  cached_network_image: ^3.4.1

  # Pin code input (OTP) text field
  pinput: ^5.0.1

  # Package for discover network connectivity status
  connectivity_plus: ^6.1.3

  # Code generator for assets, fonts, colors, …
  flutter_gen: ^5.10.0

  # A package to use fonts from fonts.google.com
  google_fonts: ^6.2.1

  # An animation package
  animate_do: ^4.1.1

  # A Flutter package for picking images from the image library,
  # and taking new pictures with the camera
  image_picker: ^1.1.2

  # Package for launching a URL on the device
  url_launcher: ^6.2.3

  # A Flutter package that provides a WebView widget.
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.22.0

  # A Flutter package to hide the keyboard when performing a gesture outside of it
  keyboard_dismisser: ^3.0.0

dev_dependencies:
  slang_build_runner: *slang_version
  build_runner: ^2.4.15
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# flutter_gen package configuration
flutter_gen:
  output: lib/core/gen/
  line_length: 80

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

